name: first workflow  # name
on: workflow_dispatch # trigger
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Done - bye!"

        
